services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Markocupic\ContaoDbBackup\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Event}

